import { deflateSync } from 'node:zlib';

export const SUPABASE_URL = 'https://wsxszbdvvtowmrnxdsrp.supabase.co';
export const SUPABASE_KEY = 'sb_publishable_JdUSYUZwX9RNdchmtUUEfw_ralc2WyT';
export const SUBJECTS = [
['agri','Agriculture','agriculture'],['ara','Arabic','arabic'],['art','Art','art'],['bio','Biology','biology'],['chem','Chemistry','chemistry'],['crs','Christian Religious Studies','christian-religious-studies'],['comm','Commerce','commerce'],['comp','Computer Studies','computer-studies'],['econ','Economics','economics'],['fre','French','french'],['geo','Geography','geography'],['gov','Government','government'],['hau','Hausa','hausa'],['hist','History','history'],['home','Home Economics','home-economics'],['igb','Igbo','igbo'],['isl','Islamic Studies','islamic-studies'],['lit','Literature in English','literature-in-english'],['math','Mathematics','mathematics'],['mus','Music','music'],['phe','Physical & Health Education','physical-and-health-education'],['phy','Physics','physics'],['acct','Principles of Account','principles-of-account'],['eng','Use of English','use-of-english'],['yor','Yoruba','yoruba']].map(([code,displayName,slug])=>({code,displayName,slug}));
const mem=globalThis.__jambVercelMemory||(globalThis.__jambVercelMemory=new Map());
export function memoryGet(key){const x=mem.get(key);if(!x||x.expiresAt<Date.now()){if(x)mem.delete(key);return null;}return x.value;}
export function memorySet(key,value,ttl=600000){mem.set(key,{value,expiresAt:Date.now()+ttl});}
export function escapeHtml(v=''){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');}
export function subjectFromToken(token){const v=String(token||'');return SUBJECTS.find(s=>s.code===v||s.slug===v)||null;}
export async function supabaseRpc(name,args={}){const res=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:SUPABASE_KEY,'content-type':'application/json','accept':'application/json'},body:JSON.stringify(args),signal:AbortSignal.timeout(7000)});const text=await res.text();let body;try{body=text?JSON.parse(text):null;}catch{body=text;}if(!res.ok)throw new Error(body?.message||body?.hint||`Exam Bank RPC ${name} returned ${res.status}`);return body;}
export async function telegram(token,method,payload={},timeoutMs=7000){const res=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(timeoutMs)});const body=await res.json().catch(()=>({}));if(!res.ok||!body?.ok)throw new Error(body?.description||`${method} failed`);return body.result;}
export async function loadConfig(configId,secret){const key=`cfg:${configId}:${secret}`,cached=memoryGet(key);if(cached)return cached;const body=await supabaseRpc('bot_get_config',{p_config_id:configId,p_secret:secret});const row=Array.isArray(body)?body[0]:body;if(!row?.telegram_token)return null;const cfg={token:row.telegram_token,groq:row.groq_key,cfAccount:row.cf_account,cfToken:row.cf_token};memorySet(key,cfg,15*60*1000);return cfg;}
export function parseBundle(raw){const lines=String(raw||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(lines.length>=5&&!lines[1].startsWith('gsk_')&&lines[2].startsWith('gsk_'))lines.splice(1,1);const token=lines[0]||'',groq=lines.find(x=>x.startsWith('gsk_'))||lines[1]||'',cfToken=lines.find(x=>x.startsWith('cfut_'))||lines[3]||'',cfAccount=lines.find((x,i)=>i>0&&x!==groq&&x!==cfToken&&/^[a-f0-9]{32}$/i.test(x))||lines[2]||'';return{token,groq,cfAccount,cfToken,lines};}
export async function getYears(subject){const key=`years:${subject.slug}`,cached=memoryGet(key);if(cached)return cached;const body=await supabaseRpc('jamb_years',{p_subject_slug:subject.slug});const years=(Array.isArray(body)?body:[]).map(x=>Number(x.year)).filter(Number.isInteger);memorySet(key,years,60*60*1000);return years;}
export async function getQuestionBatch(subject,year){const key=`pool:${subject.slug}:${year}`,cached=memoryGet(key);if(cached?.length)return cached;const body=await supabaseRpc('jamb_question_batch',{p_subject_slug:subject.slug,p_year:year==='any'?null:Number(year),p_limit:10});const list=Array.isArray(body)?body.filter(Boolean):body?[body]:[];if(!list.length)throw new Error(`No published JAMB question is available for ${subject.displayName}${year!=='any'?` in ${year}`:''}.`);memorySet(key,list,5*60*1000);return list;}
export async function getQuestionById(id){const key=`q:${id}`,cached=memoryGet(key);if(cached)return cached;const body=await supabaseRpc('jamb_question_get',{p_question_id:id});const q=Array.isArray(body)?body[0]:body;if(q)memorySet(key,q,30*60*1000);return q;}
export function pickQuestion(pool,chatId,subject,year){const key=`cursor:${chatId}:${subject.code}:${year}`;let i=Number(memoryGet(key));if(!Number.isInteger(i))i=Math.floor(Math.random()*pool.length);else i=(i+1)%pool.length;memorySet(key,i,30*60*1000);return pool[i];}
export async function setChatState(configId,secret,chatId,q,subject,year){try{await supabaseRpc('bot_set_chat_state',{p_config_id:configId,p_secret:secret,p_chat_id:Number(chatId),p_question_id:q.id,p_subject_slug:subject.slug,p_year:year==='any'?null:Number(year)});}catch(e){console.error('state set',e);}}
export async function getChatState(configId,secret,chatId){const body=await supabaseRpc('bot_get_chat_state',{p_config_id:configId,p_secret:secret,p_chat_id:Number(chatId)});return Array.isArray(body)?body[0]:body;}
export function subjectMenu(page=0){const size=10,pages=Math.ceil(SUBJECTS.length/size),p=Math.min(Math.max(0,Number(page)||0),pages-1),visible=SUBJECTS.slice(p*size,p*size+size),rows=[];for(let i=0;i<visible.length;i+=2)rows.push(visible.slice(i,i+2).map(s=>({text:s.displayName,callback_data:`s:${s.code}`})));const nav=[];if(p>0)nav.push({text:'⬅️ Previous',callback_data:`sp:${p-1}`});nav.push({text:`${p+1}/${pages}`,callback_data:'noop'});if(p<pages-1)nav.push({text:'Next ➡️',callback_data:`sp:${p+1}`});rows.push(nav);return{text:`🎓 <b>JAMB Practice Bot</b>\n\nChoose a subject below.\n\n<b>${SUBJECTS.length} subjects available</b>\n⚡ Fast Exam Bank mode\n<i>Questions served from our own Supabase Exam Bank</i>`,reply_markup:{inline_keyboard:rows}};}
export function yearMenu(subject,years,page=0){const size=12,pages=Math.max(1,Math.ceil(years.length/size)),p=Math.min(Math.max(0,Number(page)||0),pages-1),visible=years.slice(p*size,p*size+size),rows=[[{text:'🎯 Random question — any year',callback_data:`q:${subject.code}:any`}]];for(let i=0;i<visible.length;i+=3)rows.push(visible.slice(i,i+3).map(y=>({text:String(y),callback_data:`q:${subject.code}:${y}`})));if(pages>1){const nav=[];if(p>0)nav.push({text:'⬅️',callback_data:`yp:${subject.code}:${p-1}`});nav.push({text:`${p+1}/${pages}`,callback_data:'noop'});if(p<pages-1)nav.push({text:'➡️',callback_data:`yp:${subject.code}:${p+1}`});rows.push(nav);}rows.push([{text:'📚 All subjects',callback_data:'subjects'}]);return{text:`📘 <b>${escapeHtml(subject.displayName)}</b>\n\nChoose a JAMB year or practise from any year.${years.length?`\n\n${years.length} years currently available in Exam Bank.`:'\n\nNo year-specific questions are published yet; try Random question.'}`,reply_markup:{inline_keyboard:rows}};}
function choices(q){return Array.isArray(q?.choices)?q.choices.map(c=>({label:String(c.label||'').toLowerCase(),text:String(c.text||''),isCorrect:c.isCorrect===true})).filter(c=>/^[a-e]$/.test(c.label)):[];}
export function officialAnswer(q){const c=choices(q).find(x=>x.isCorrect);if(c)return c.label;const raw=String(q?.answerText||'').trim();if(/^[a-e]$/i.test(raw))return raw.toLowerCase();const byText=choices(q).find(x=>x.text.trim().toLowerCase()===raw.toLowerCase());return byText?.label||'';}
export function questionImage(q){const a=Array.isArray(q?.assets)?q.assets.find(x=>x?.url||x?.path):null;if(!a)return'';if(a.url)return String(a.url);if(a.bucket&&a.path)return`${SUPABASE_URL}/storage/v1/object/public/${encodeURIComponent(a.bucket)}/${String(a.path).split('/').map(encodeURIComponent).join('/')}`;return'';}
export function questionHtml(q,subject){const cs=choices(q),passage=q?.passage?.content?`<b>Passage</b>\n${escapeHtml(q.passage.content)}\n\n`:'',opts=cs.map(c=>`<b>${c.label.toUpperCase()}.</b> ${escapeHtml(c.text)}`).join('\n');let text=`<b>${escapeHtml(subject.displayName)} — JAMB${q?.year?` ${q.year}`:''}</b>\n\n${passage}${escapeHtml(q?.text||'Question unavailable')}\n\n${opts}\n\n<i>Source: Exam Bank</i>`;if(text.length>4000)text=text.slice(0,3990)+'…';return text;}
export function questionButtons(q,subject,year){const correct=officialAnswer(q)||'x',qid=String(q.id),answers=choices(q).map(c=>({text:c.label.toUpperCase(),callback_data:`ans:${c.label}:${correct}:${subject.code}:${year}:${qid}`})),rows=[answers];rows.push([{text:'💡 Explain',callback_data:`e:${qid}`},{text:'🎨 Diagram / Graph',callback_data:`v:${qid}`}]);if(['math','phy','chem'].includes(subject.code))rows.push([{text:'🧮 Render Maths',callback_data:`m:${qid}`}]);rows.push([{text:'➡️ Next',callback_data:`n:${subject.code}:${year}`},{text:'📅 Change Year',callback_data:`s:${subject.code}`}]);rows.push([{text:'📚 Subjects',callback_data:'subjects'}]);return{inline_keyboard:rows};}
export function resultButtons(qid,subjectCode,year){return{inline_keyboard:[[{text:'💡 Explain',callback_data:`e:${qid}`},{text:'🎨 Visual',callback_data:`v:${qid}`}],[{text:'➡️ Next Question',callback_data:`n:${subjectCode}:${year}`},{text:'📚 Subjects',callback_data:'subjects'}]]};}
function solutionPrompt(q,custom=''){const cs=choices(q).map(c=>`${c.label.toUpperCase()}. ${c.text}`).join('\n');return`You are a fast Nigerian JAMB tutor. Solve the question independently. Do not reveal hidden chain-of-thought. Give concise educational steps only. Return ONLY valid JSON with keys answer, explanation, steps, key_latex, visualization_kind, visualization_code, confidence. answer must be A-E or empty. visualization_kind must be none, mermaid, or vega. Use a visual only when it genuinely helps.\n\nQuestion: ${q?.text||''}\n${q?.passage?.content?`Passage: ${q.passage.content}\n`:''}Options:\n${cs}\n${custom?`Student request: ${custom}\n`:''}`;}
function extractAiJson(text){const raw=String(text||'').trim().replace(/^```(?:json)?/i,'').replace(/```$/,'').trim();try{return JSON.parse(raw);}catch{const a=raw.indexOf('{'),b=raw.lastIndexOf('}');if(a>=0&&b>a)try{return JSON.parse(raw.slice(a,b+1));}catch{}return{answer:'',explanation:raw,steps:[],key_latex:'',visualization_kind:'none',visualization_code:'',confidence:0};}}
async function groqSolve(q,key,custom=''){const image=questionImage(q),prompt=solutionPrompt(q,custom);let content=prompt;if(image)content=[{type:'text',text:prompt},{type:'image_url',image_url:{url:image}}];const res=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'content-type':'application/json'},body:JSON.stringify({model:'qwen/qwen3.8-27b',messages:[{role:'user',content}],temperature:0.2,max_completion_tokens:850,reasoning_effort:'low',reasoning_format:'hidden',response_format:{type:'json_object'}}),signal:AbortSignal.timeout(18000)});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body?.error?.message||`Groq ${res.status}`);return{...extractAiJson(body?.choices?.[0]?.message?.content),provider:'Groq Qwen3.8-27B'};}
async function cloudflareSolve(q,account,token,custom=''){const res=await fetch(`https://api.cloudflare.com/client/v4/accounts/${encodeURIComponent(account)}/ai/run/@cf/google/gemma-4-26b-a4b-it`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({messages:[{role:'user',content:solutionPrompt(q,custom)}],max_tokens:850,temperature:0.2}),signal:AbortSignal.timeout(20000)});const body=await res.json().catch(()=>({}));if(!res.ok||body?.success===false)throw new Error(body?.errors?.[0]?.message||`Cloudflare ${res.status}`);const text=body?.result?.response||body?.result?.text||body?.result?.choices?.[0]?.message?.content||'';return{...extractAiJson(text),provider:'Cloudflare Gemma 4 26B'};}
export async function aiSolve(q,cfg,custom=''){const cacheKey=`ai:${q.id}:${custom}`,cached=memoryGet(cacheKey);if(cached)return cached;let result;try{result=await groqSolve(q,cfg.groq,custom);}catch(e){console.warn('Groq fallback',e?.message);result=await cloudflareSolve(q,cfg.cfAccount,cfg.cfToken,custom);}memorySet(cacheKey,result,60*60*1000);return result;}
export function explanationHtml(q,ai){const official=officialAnswer(q).toUpperCase(),model=String(ai?.answer||'').trim().toUpperCase();if(official&&model&&official!==model)return`⚠️ <b>Answer check mismatch</b>\n\nExam Bank answer: <b>${escapeHtml(official)}</b>\nAI answer: <b>${escapeHtml(model)}</b>\n\nI won't present the AI explanation as authoritative for this item. It should be reviewed.\n\n<i>${escapeHtml(ai?.provider||'AI tutor')}</i>`;const steps=Array.isArray(ai?.steps)&&ai.steps.length?`\n\n<b>Steps</b>\n${ai.steps.slice(0,6).map((x,i)=>`${i+1}. ${escapeHtml(x)}`).join('\n')}`:'';return`💡 <b>Worked Explanation</b>${official?`\n\nCorrect answer: <b>${escapeHtml(official)}</b>`:''}\n\n${escapeHtml(ai?.explanation||q?.explanation||'No explanation available.')}${steps}\n\n<i>${escapeHtml(ai?.provider||'AI tutor')}</i>`;}
export function latexUrl(latex){if(!latex)return'';return`https://latex.codecogs.com/png.image?%5Cdpi%7B180%7D%20${encodeURIComponent(String(latex).slice(0,1000))}`;}
export function visualUrl(ai){const kind=String(ai?.visualization_kind||'none').toLowerCase(),code=String(ai?.visualization_code||'').trim();if((kind==='mermaid'||kind==='vega')&&code){const encoded=deflateSync(Buffer.from(code)).toString('base64url');return`https://kroki.io/${kind}/png/${encoded}`;}return latexUrl(ai?.key_latex||'');}
