import Link from 'next/link';

const Brand=()=> <Link href="/" className="brand"><span className="brandMark">AD</span><span>Acres of Diamond<small>Multipurpose Cooperative Society</small></span></Link>;

export default function Home(){
 const features=[
  ['01','Property Thrift','Build toward property ownership with the structured ₦10,000 weekly plan for 50 weeks, tracked separately and transparently.'],
  ['02','Member savings','Keep flexible participative savings with a complete ledger, history and clear loan-security treatment.'],
  ['03','Share capital','Your ownership stake stays separate from spendable wallet funds and savings, so every naira has a clear purpose.'],
  ['04','Responsible credit','Apply after eligibility, use your savings/shares and approved guarantors as security, and see a reducing-balance schedule.'],
  ['05','Transparent approvals','Membership, loans and withdrawals use maker-checker review with independent approvals and immutable audit trails.'],
  ['06','Digital records','Access receipts, statements, transaction history, notifications, support and member records from one mobile-ready account.'],
 ];
 return <>
  <header className="publicHeader"><div className="container inner"><Brand/><nav className="publicNav"><a href="#membership">Membership</a><a href="#products">Savings & shares</a><a href="#loans">Loans</a><a href="#security">Security</a></nav><div className="headerActions"><Link className="btn" href="/login">Log in</Link><Link className="btn primary" href="/register">Become a member</Link></div></div></header>
  <main>
   <section className="heroPublic"><div className="container heroGrid"><div><p className="eyebrow">Member-owned · asset-focused · transparently managed</p><h1 className="display">Build assets together, one disciplined contribution at a time.</h1><p className="lead">Acres of Diamond is a modern cooperative platform for property thrift, savings, member shares and responsible loans—built around clear rules, verifiable records and collective strength.</p><div className="heroActions"><Link className="btn primary" href="/register">Start membership</Link><Link className="btn" href="/login">Open member portal</Link></div><div className="trustRow"><span>✓ ₦10,000 registration</span><span>✓ ₦10,000 minimum shares</span><span>✓ ₦10,000 weekly property thrift</span></div></div><div className="journeyCard"><p className="eyebrow">Membership journey</p><h2 style={{margin:'8px 0 0'}}>A clear path from applicant to active member.</h2>{['Create and verify your account','Complete profile, KYC and next-of-kin','Read and accept the current bye-laws','Pay registration fee + minimum share capital','Receive two independent approvals','Unlock the full member platform'].map((x,i)=><div className="journeyStep" key={x}><span className="stepNo">{i+1}</span><b>{x}</b></div>)}</div></div></section>
   <section id="products" className="section"><div className="container"><div className="sectionHead"><p className="eyebrow">One cooperative. Distinct balances.</p><h2 className="display">Know exactly what every naira means.</h2><p>Wallet funds, participative savings, Property Thrift, share capital, pledged security, loan balances and fees are treated as different financial buckets—not one confusing balance.</p></div><div className="featureGrid">{features.map(([n,t,d])=><article className="card featureCard" key={t}><span className="num">{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
   <section id="membership"><div className="container"><div className="propertyBand"><div><p className="eyebrow" style={{color:'#9ee0bd'}}>Structured asset building</p><h2 className="display">Property Thrift that turns consistency into visible progress.</h2><p>Contribute ₦10,000 weekly for 50 weeks. Your dashboard tracks installments, total contribution, next due date and progress toward the ₦500,000 cycle target.</p><Link href="/register" className="btn" style={{marginTop:10}}>Join the cooperative</Link></div><div><div className="propertyFigure">₦500k</div><small style={{color:'#b8d1c5'}}>50 × ₦10,000 weekly</small></div></div></div></section>
   <section id="loans" className="section"><div className="container"><div className="sectionHead"><p className="eyebrow">Responsible credit</p><h2 className="display">Loans designed around capacity, security and accountability.</h2><p>Eligible members can apply after qualifying savings history. The platform evaluates member security, guarantor pledges, tenure and policy rules before maker-checker approval and disbursement.</p></div><div className="featureGrid"><article className="card featureCard"><span className="num">01</span><h3>Eligibility first</h3><p>Current rules require qualifying savings history before borrowing. Policy versions are recorded with each decision.</p></article><article className="card featureCard"><span className="num">02</span><h3>Clear repayment schedule</h3><p>Reducing-balance installments separate principal, interest and any penalties so the member can understand the contract.</p></article><article className="card featureCard"><span className="num">03</span><h3>Guarantor protection</h3><p>Guarantors see the commitment before accepting, and pledged security remains tracked until the exposure is resolved.</p></article></div></div></section>
   <section id="security"><div className="container propertyBand" style={{background:'#f1f8f4',color:'var(--ink)',border:'1px solid var(--line)'}}><div><p className="eyebrow">Built for trust</p><h2 className="display">Financial records should be difficult to manipulate and easy to explain.</h2><p style={{color:'var(--muted)'}}>V4 uses row-level access controls, role permissions, maker-checker approvals, a double-entry ledger, transaction PIN protection, versioned policies and bye-laws, provider event deduplication and audit logs.</p></div><Link href="/login" className="btn primary">Go to portal</Link></div></section>
  </main>
  <footer className="footer"><div className="container footerGrid"><div><Brand/><p>Acres of Diamond Multipurpose Cooperative Society. Building disciplined savings, responsible credit and pathways toward member asset ownership.</p></div><div><b>Members</b><p><Link href="/register">Become a member</Link><br/><Link href="/login">Member login</Link><br/><Link href="/onboarding">Onboarding</Link></p></div><div><b>Platform</b><p>Secure records<br/>Transparent approvals<br/>Member support</p></div></div></footer>
 </>
}
