import { waitUntil } from '@vercel/functions';
import { telegram,loadConfig,subjectMenu,subjectFromToken,getYears,yearMenu,getQuestionBatch,pickQuestion,questionHtml,questionButtons,resultButtons,getQuestionById,aiSolve,explanationHtml,visualUrl,latexUrl,setChatState,getChatState,escapeHtml,questionImage } from '../lib/core.js';

async function edit(token,cb,text,reply_markup){return telegram(token,'editMessageText',{chat_id:cb.message.chat.id,message_id:cb.message.message_id,text,parse_mode:'HTML',reply_markup});}
async function send(token,chatId,text,reply_markup){return telegram(token,'sendMessage',{chat_id:chatId,text,parse_mode:'HTML',reply_markup,disable_web_page_preview:true});}
async function sendQuestion(token,configId,secret,chatId,subject,year){const pool=await getQuestionBatch(subject,year),q=pickQuestion(pool,chatId,subject,year),text=questionHtml(q,subject),buttons=questionButtons(q,subject,year),image=questionImage(q);if(image&&text.length<=950){try{await telegram(token,'sendPhoto',{chat_id:chatId,photo:image,caption:text,parse_mode:'HTML',reply_markup:buttons});}catch{await send(token,chatId,text,buttons);}}else await send(token,chatId,text,buttons);await setChatState(configId,secret,chatId,q,subject,year);}
async function explain(token,chatId,qid,cfg,visual=false,math=false){const q=await getQuestionById(qid);if(!q){await send(token,chatId,'Question not found in Exam Bank.');return;}if(math){const ai=await aiSolve(q,cfg);const url=latexUrl(ai?.key_latex||'');if(url)await telegram(token,'sendPhoto',{chat_id:chatId,photo:url,caption:'🧮 Mathematical view'});else await send(token,chatId,'I could not identify a useful formula to render for this question.');return;}const ai=await aiSolve(q,cfg);if(visual){const url=visualUrl(ai);if(url)await telegram(token,'sendPhoto',{chat_id:chatId,photo:url,caption:'🎨 AI-generated learning visual'});else await send(token,chatId,'This solution does not need a useful diagram or graph. Tap Explain for the worked solution.');return;}await send(token,chatId,explanationHtml(q,ai));}
async function ask(token,configId,secret,chatId,cfg,prompt){await telegram(token,'sendChatAction',{chat_id:chatId,action:'typing'}).catch(()=>{});const st=await getChatState(configId,secret,chatId);if(!st?.question_id){await send(token,chatId,'Open a question first with /start, then use /ask.');return;}const q=await getQuestionById(st.question_id);if(!q){await send(token,chatId,'The current question is unavailable.');return;}const ai=await aiSolve(q,cfg,prompt);await send(token,chatId,explanationHtml(q,ai));}

export default {async fetch(req){
  if(req.method!=='POST')return new Response('JAMB Telegram webhook',{status:200});
  const url=new URL(req.url),configId=url.searchParams.get('cfg')||'',secret=req.headers.get('x-telegram-bot-api-secret-token')||'';
  if(!configId||!secret)return new Response('Forbidden',{status:403});
  let cfg;try{cfg=await loadConfig(configId,secret);}catch(e){console.error('config',e);return new Response('Forbidden',{status:403});}if(!cfg)return new Response('Forbidden',{status:403});
  let update;try{update=await req.json();}catch{return Response.json({ok:true});}
  const cb=update?.callback_query,msg=update?.message;
  if(cb){const chatId=cb?.message?.chat?.id,data=String(cb.data||'');await telegram(cfg.token,'answerCallbackQuery',{callback_query_id:cb.id,text:(data.startsWith('e:')||data.startsWith('v:')||data.startsWith('m:'))?'Working…':undefined}).catch(()=>{});if(!chatId)return Response.json({ok:true});if(data==='noop')return Response.json({ok:true});if(data==='subjects'){const menu=subjectMenu(0);waitUntil(edit(cfg.token,cb,menu.text,menu.reply_markup).catch(console.error));return Response.json({ok:true});}if(data.startsWith('sp:')){const menu=subjectMenu(Number(data.slice(3)));waitUntil(edit(cfg.token,cb,menu.text,menu.reply_markup).catch(console.error));return Response.json({ok:true});}if(data.startsWith('s:')){const s=subjectFromToken(data.slice(2));if(s)waitUntil((async()=>{const years=await getYears(s);const menu=yearMenu(s,years,0);await edit(cfg.token,cb,menu.text,menu.reply_markup);})().catch(async e=>send(cfg.token,chatId,`❌ ${escapeHtml(e.message)}`)));return Response.json({ok:true});}if(data.startsWith('yp:')){const [,code,p]=data.split(':'),s=subjectFromToken(code);if(s)waitUntil((async()=>{const years=await getYears(s),menu=yearMenu(s,years,Number(p));await edit(cfg.token,cb,menu.text,menu.reply_markup);})().catch(console.error));return Response.json({ok:true});}if(data.startsWith('q:')||data.startsWith('n:')){const [,code,year]=data.split(':'),s=subjectFromToken(code);if(s)waitUntil(sendQuestion(cfg.token,configId,secret,chatId,s,year).catch(async e=>send(cfg.token,chatId,`❌ ${escapeHtml(e.message)}`)));return Response.json({ok:true});}if(data.startsWith('ans:')){const parts=data.split(':'),selected=parts[1],correct=parts[2],code=parts[3],year=parts[4],qid=parts.slice(5).join(':');const good=correct!=='x'&&selected===correct,text=correct==='x'?`✅ Answer recorded: <b>${selected.toUpperCase()}</b>.`:good?`✅ <b>Correct!</b> You chose ${selected.toUpperCase()}.`:`❌ <b>Incorrect.</b> You chose ${selected.toUpperCase()}. Correct answer: <b>${correct.toUpperCase()}</b>.`;waitUntil(send(cfg.token,chatId,text,resultButtons(qid,code,year)).catch(console.error));return Response.json({ok:true});}if(data.startsWith('e:')||data.startsWith('v:')||data.startsWith('m:')){const mode=data[0],qid=data.slice(2);waitUntil(explain(cfg.token,chatId,qid,cfg,mode==='v',mode==='m').catch(async e=>send(cfg.token,chatId,`❌ AI tutor: ${escapeHtml(e.message)}`)));return Response.json({ok:true});}return Response.json({ok:true});}
  if(msg){const chatId=msg?.chat?.id,text=String(msg?.text||'').trim();if(!chatId)return Response.json({ok:true});if(text==='/start'||text.startsWith('/start ')){const m=subjectMenu(0);waitUntil(send(cfg.token,chatId,m.text,m.reply_markup).catch(console.error));return Response.json({ok:true});}if(text==='/help'){waitUntil(send(cfg.token,chatId,'🎓 <b>JAMB Practice Bot</b>\n\n/start — choose a subject and year\n/ask &lt;question&gt; — ask the AI tutor about your current question\n\nQuestions: Supabase Exam Bank\nAI: Groq Qwen3.8-27B with Cloudflare Gemma 4 26B fallback').catch(console.error));return Response.json({ok:true});}if(text.startsWith('/ask')){const prompt=text.replace(/^\/ask(?:@\w+)?\s*/i,'').trim()||'Explain this question clearly and show the fastest exam method.';waitUntil(ask(cfg.token,configId,secret,chatId,cfg,prompt).catch(async e=>send(cfg.token,chatId,`❌ ${escapeHtml(e.message)}`)));return Response.json({ok:true});}waitUntil(send(cfg.token,chatId,'Send /start to begin JAMB practice.').catch(console.error));}
  return Response.json({ok:true});
}};
