'use client';
import {useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {supabase} from '../../lib/supabase';

type AnyObj=Record<string,any>;
const money=(v:any)=>`₦${Number(v||0).toLocaleString('en-NG',{maximumFractionDigits:2})}`;
const navMember=[['dashboard','Overview'],['onboarding','Onboarding'],['wallet','Wallet'],['savings','Savings'],['shares','Shares'],['loans','Loans'],['withdrawals','Withdrawals'],['transactions','Transactions'],['security','Security']];
const navAdmin=[['admin-overview','Admin overview'],['approvals','Approvals'],['members','Members'],['operations','Operations'],['audit','Audit & controls']];
function Metric({label,value,sub}:{label:string,value:any,sub?:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>}
function Empty({text='Nothing to show yet.'}:{text?:string}){return <div className="empty">{text}</div>}
function Status({value}:{value:any}){const s=String(value||'unknown');return <span className={`status ${s.replace(/\s/g,'-')}`}>{s.replaceAll('_',' ')}</span>}
function Card({title,children,action}:{title:string,children:React.ReactNode,action?:React.ReactNode}){return <section className="card"><div className="cardHead"><h3>{title}</h3>{action}</div>{children}</section>}

export default function Portal(){
 const router=useRouter(); const[section,setSection]=useState('dashboard');const[menu,setMenu]=useState(false);const[data,setData]=useState<AnyObj|null>(null);const[admin,setAdmin]=useState<AnyObj|null>(null);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState('');const[search,setSearch]=useState('');const[results,setResults]=useState<any[]>([]);const[selected,setSelected]=useState<AnyObj|null>(null);const[amount,setAmount]=useState('');const[pinModal,setPinModal]=useState<{rpc:string,args:AnyObj,title:string}|null>(null);const[pin,setPin]=useState('');
 async function load(){setBusy(true);setNotice('');const{data:{session}}=await supabase.auth.getSession();if(!session){router.replace('/login');return}await supabase.rpc('start_app_session',{p_device_label:navigator.userAgent.slice(0,100)});const snap=await supabase.rpc('member_complete_snapshot');if(snap.error){setNotice(snap.error.message);setBusy(false);return}setData(snap.data);const role=snap.data?.portal?.profile?.role;if(['admin','super_admin'].includes(role)){const a=await supabase.rpc('admin_control_center_snapshot');if(!a.error)setAdmin(a.data)}setBusy(false)}
 useEffect(()=>{load();const id=setInterval(()=>supabase.rpc('touch_app_session'),120000);return()=>clearInterval(id)},[]);
 const portal=data?.portal||{};const profile=portal.profile||{};const role=profile.role||'member';const isAdmin=['admin','super_admin'].includes(role);const isSuper=role==='super_admin';const nav=useMemo(()=>isAdmin?[...navMember,...navAdmin]:navMember,[isAdmin]);
 async function call(rpc:string,args:AnyObj={}){setBusy(true);setNotice('');const r=await supabase.rpc(rpc,args);setBusy(false);if(r.error){setNotice(r.error.message);return null}setNotice('Action completed successfully.');await load();return r.data}
 async function logout(){await supabase.rpc('end_app_session',{p_reason:'user_logout'});await supabase.auth.signOut();router.replace('/login')}
 function debit(title:string,rpc:string,args:AnyObj){setPin('');setPinModal({title,rpc,args})}
 async function confirmDebit(){if(!pinModal||pin.length!==4)return;await call(pinModal.rpc,{...pinModal.args,p_pin:pin});setPinModal(null);setPin('')}
 async function memberSearch(){if(!search.trim())return;setBusy(true);const r=await supabase.rpc('admin_search_members',{p_query:search,p_limit:30,p_offset:0});setBusy(false);if(r.error)return setNotice(r.error.message);setResults(Array.isArray(r.data)?r.data:r.data?.items||[])}
 async function openMember(id:string){setBusy(true);const r=await supabase.rpc('admin_member_360',{p_user:id});setBusy(false);if(r.error)return setNotice(r.error.message);setSelected(r.data)}
 const apps=admin?.applications||[];const loans=admin?.loans||[];const withdrawals=admin?.withdrawals||[];const payments=admin?.payments||[];const complaints=admin?.complaints||[];
 return <div className="shell"><aside className={`sidebar ${menu?'open':''}`}><div className="brand"><div className="logoBox">AD</div><div><b>Acres of Diamond</b><small>Multipurpose Cooperative</small></div></div><nav>{nav.map(([key,label])=><button key={key} className={section===key?'active':''} onClick={()=>{setSection(key);setMenu(false)}}>{label}</button>)}</nav><button className="signout" onClick={logout}>Sign out</button></aside><div className="main"><header className="topbar"><button className="menuBtn" onClick={()=>setMenu(!menu)}>☰</button><div><span className="eyebrow">{isAdmin?'CONTROL CENTER':'MEMBER PORTAL'}</span><h1>{nav.find(n=>n[0]===section)?.[1]||'Portal'}</h1></div><div className="userChip"><span>{profile.first_name||'Member'}</span><small>{profile.member_id||role}</small></div></header>{notice&&<div className="toast">{notice}</div>}{busy&&<div className="loadingBar"/>}<main className="page">
 {section==='dashboard'&&<><div className="heroCard"><div><span className="eyebrow">YOUR COOPERATIVE ACCOUNT</span><h2>Welcome back, {profile.first_name||'Member'}.</h2><p>Track your money, membership and obligations from one place.</p></div><Status value={profile.status}/></div><div className="metrics"><Metric label="Wallet" value={money(portal.wallet_balance)}/><Metric label="Savings" value={money(portal.total_contributions)}/><Metric label="Share capital" value={money(portal.share_capital)}/><Metric label="Outstanding loans" value={money(portal.outstanding_loans)}/></div><div className="grid2"><Card title="Account status"><div className="facts"><div><span>Role</span><b>{role.replace('_',' ')}</b></div><div><span>Member ID</span><b>{profile.member_id||'Pending'}</b></div><div><span>Transaction PIN</span><b>{portal.pin_status?.pin_set?'Set':'Not set'}</b></div><div><span>Pledged security</span><b>{money(portal.pledged_security)}</b></div></div></Card><Card title="Recent activity">{(portal.recent_transactions||[]).slice(0,5).map((t:any)=><div className="list" key={t.id}><div><b>{t.description||t.type}</b><small>{t.reference}</small></div><strong>{money(t.amount)}</strong></div>)}{!(portal.recent_transactions||[]).length&&<Empty/>}</Card></div></>}
 {section==='onboarding'&&<Card title="Membership onboarding"><p className="muted">Complete your registration, KYC, bye-law acceptance, fees and share capital before final approval.</p><div className="stepGrid">{[['Application',data?.onboarding?.status?.application_status],['NIN',data?.onboarding?.status?.nin_status],['Bye-laws',data?.onboarding?.status?.bylaws_accepted?'accepted':'pending'],['Registration fee',data?.onboarding?.status?.registration_fee_paid?'paid':'pending']].map(([a,b])=><div className="step" key={a}><span>{a}</span><Status value={b}/></div>)}</div><div className="actions"><button className="btn" onClick={()=>call('accept_current_bylaws')}>Accept current bye-laws</button><button className="btn primary" onClick={()=>call('submit_membership_application')}>Submit application</button></div></Card>}
 {section==='wallet'&&<Card title="Wallet"><div className="balance">{money(portal.wallet_balance)}</div><p className="muted">Funding does not require a transaction PIN. Wallet debits ask for your PIN only at confirmation.</p><div className="inlineForm"><input inputMode="decimal" placeholder="Amount" value={amount} onChange={e=>setAmount(e.target.value)}/><button className="btn primary" onClick={async()=>{const r=await call('paystack_initialize',{p_amount:Number(amount)});if(r?.authorization_url)location.href=r.authorization_url}}>Fund with Paystack</button></div></Card>}
 {section==='savings'&&<Card title="Savings"><div className="balance">{money(portal.total_contributions)}</div><div className="cardsMini">{(portal.savings_schemes||[]).map((s:any)=><div className="mini" key={s.id}><b>{s.name}</b><small>Minimum {money(s.minimum_contribution)}</small><button className="btn" onClick={()=>debit(`Save to ${s.name}`,'save_to_scheme',{p_scheme:s.id,p_amount:Number(amount)})}>Save from wallet</button></div>)}</div><input inputMode="decimal" placeholder="Amount to save" value={amount} onChange={e=>setAmount(e.target.value)}/></Card>}
 {section==='shares'&&<Card title="Share capital"><div className="balance">{money(portal.share_capital)}</div><div className="inlineForm"><input inputMode="numeric" placeholder="Share units" value={amount} onChange={e=>setAmount(e.target.value)}/><button className="btn primary" onClick={()=>debit('Buy shares','buy_shares',{p_units:Number(amount)})}>Buy shares</button></div></Card>}
 {section==='loans'&&<Card title="Loans">{(portal.loans||[]).map((l:any)=><div className="list" key={l.id}><div><b>{money(l.amount)}</b><small>{l.term_months} months · outstanding {money(l.outstanding)}</small></div><Status value={l.status}/></div>)}{!(portal.loans||[]).length&&<Empty/>}</Card>}
 {section==='withdrawals'&&<Card title="Withdrawals">{(portal.withdrawals||[]).map((w:any)=><div className="list" key={w.id}><div><b>{money(w.amount)}</b><small>{w.bank_name}</small></div><Status value={w.status}/></div>)}{!(portal.withdrawals||[]).length&&<Empty/>}</Card>}
 {section==='transactions'&&<Card title="Transactions">{(portal.recent_transactions||[]).map((t:any)=><div className="list" key={t.id}><div><b>{t.description||t.type}</b><small>{t.reference} · {t.created_at?new Date(t.created_at).toLocaleString():''}</small></div><strong>{money(t.amount)}</strong></div>)}{!(portal.recent_transactions||[]).length&&<Empty/>}</Card>}
 {section==='security'&&<Card title="Security"><p className="muted">Transaction PIN protects member-initiated wallet debits. Admin MFA has been removed from this version.</p><div className="facts"><div><span>PIN status</span><b>{portal.pin_status?.pin_set?'Set':'Not set'}</b></div><div><span>PIN locked</span><b>{portal.pin_status?.locked?'Yes':'No'}</b></div></div></Card>}
 {section==='admin-overview'&&isAdmin&&<><div className="heroCard adminHero"><div><span className="eyebrow">{isSuper?'SUPER ADMIN':'ADMIN'} WORKSPACE</span><h2>Cooperative operations at a glance.</h2><p>Review member activity, approvals and operational risk from one dashboard.</p></div><button className="btn" onClick={load}>Refresh</button></div><div className="metrics"><Metric label="Membership queue" value={apps.length}/><Metric label="Loan queue" value={loans.length}/><Metric label="Withdrawals" value={withdrawals.length}/><Metric label="Payment reviews" value={payments.length}/></div><div className="grid2"><Card title="Approval workload"><div className="facts"><div><span>Applications</span><b>{apps.length}</b></div><div><span>Loans</span><b>{loans.length}</b></div><div><span>Withdrawals</span><b>{withdrawals.length}</b></div><div><span>Complaints</span><b>{complaints.length}</b></div></div></Card><Card title="Administration"><p className="muted">Maker-checker, role controls, audit trails and session revocation remain active. MFA is disabled.</p><div className="actions"><button className="btn" onClick={()=>setSection('members')}>Find member</button><button className="btn primary" onClick={()=>setSection('approvals')}>Review queues</button></div></Card></div></>}
 {section==='approvals'&&isAdmin&&<div className="stack"><Card title="Membership approvals">{apps.map((x:any)=><div className="list" key={x.user_id}><div><b>{`${x.first_name||''} ${x.last_name||''}`.trim()||x.member_id||'Applicant'}</b><small>{x.member_id||'Awaiting member ID'}</small></div><div className="row"><button className="btn danger" onClick={()=>call('review_membership_application',{p_user:x.user_id,p_decision:'reject',p_note:'Rejected in admin portal'})}>Reject</button><button className="btn primary" onClick={()=>call('review_membership_application',{p_user:x.user_id,p_decision:'approve',p_note:'Approved in admin portal'})}>Approve</button></div></div>)}{!apps.length&&<Empty/>}</Card><Card title="Loan approvals">{loans.map((x:any)=><div className="list" key={x.id}><div><b>{money(x.amount)}</b><small>{x.first_name} {x.last_name}</small></div><div className="row"><button className="btn danger" onClick={()=>call('review_loan',{p_loan_id:x.id,p_decision:'reject',p_approved_amount:null,p_note:'Rejected in admin portal'})}>Reject</button><button className="btn primary" onClick={()=>call('review_loan',{p_loan_id:x.id,p_decision:'approve',p_approved_amount:x.amount,p_note:'Approved in admin portal'})}>Approve</button></div></div>)}{!loans.length&&<Empty/>}</Card><Card title="Withdrawal approvals">{withdrawals.map((x:any)=><div className="list" key={x.id}><div><b>{money(x.amount)}</b><small>{x.bank_name} · {x.account_name}</small></div><div className="row"><button className="btn danger" onClick={()=>call('review_withdrawal',{p_withdrawal_id:x.id,p_decision:'reject',p_note:'Rejected in admin portal'})}>Reject</button><button className="btn primary" onClick={()=>call('review_withdrawal',{p_withdrawal_id:x.id,p_decision:'approve',p_note:'Approved in admin portal'})}>Approve</button></div></div>)}{!withdrawals.length&&<Empty/>}</Card></div>}
 {section==='members'&&isAdmin&&<><Card title="Member search"><div className="searchRow"><input placeholder="Name, member ID, email or phone" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&memberSearch()}/><button className="btn primary" onClick={memberSearch}>Search</button></div>{results.map((m:any)=><div className="list clickable" key={m.user_id||m.id} onClick={()=>openMember(m.user_id||m.id)}><div><b>{m.first_name} {m.last_name}</b><small>{m.member_id||m.email||m.phone}</small></div><Status value={m.status}/></div>)}</Card>{selected&&<Card title="Member 360"><div className="member360"><pre>{JSON.stringify(selected,null,2)}</pre></div><div className="actions"><button className="btn danger" onClick={()=>call('admin_revoke_member_sessions',{p_user:selected.profile?.id||selected.user_id,p_reason:'Administrative security action'})}>Revoke sessions</button><button className="btn" onClick={()=>call('admin_reset_member_pin',{p_user:selected.profile?.id||selected.user_id})}>Reset transaction PIN</button>{isSuper&&<><button className="btn" onClick={()=>call('set_member_role',{p_user:selected.profile?.id||selected.user_id,p_role:'admin'})}>Make admin</button><button className="btn" onClick={()=>call('set_member_role',{p_user:selected.profile?.id||selected.user_id,p_role:'member'})}>Make member</button></>}</div></Card>}</>}
 {section==='operations'&&isAdmin&&<div className="grid2"><Card title="Payment reviews">{payments.map((x:any)=><div className="list" key={x.id}><div><b>{money(x.amount)}</b><small>{x.method||x.provider} · {x.external_reference}</small></div><Status value={x.status}/></div>)}{!payments.length&&<Empty/>}</Card><Card title="Complaints">{complaints.map((x:any)=><div className="list" key={x.id}><div><b>{x.subject||'Complaint'}</b><small>{x.category||''}</small></div><Status value={x.status}/></div>)}{!complaints.length&&<Empty/>}</Card></div>}
 {section==='audit'&&isAdmin&&<><Card title="Audit & security controls" action={isSuper?<button className="btn" onClick={async()=>{const r=await supabase.rpc('superadmin_recent_audit',{p_limit:50});if(!r.error)setSelected({audit:r.data})}}>Load audit</button>:undefined}><div className="facts"><div><span>Admin MFA</span><b>Disabled</b></div><div><span>Maker-checker</span><b>Enabled</b></div><div><span>Member transaction PIN</span><b>Enabled</b></div><div><span>Role</span><b>{role.replace('_',' ')}</b></div></div>{isSuper&&<div className="actions"><button className="btn" onClick={()=>call('superadmin_set_session_policy',{p_admin_max_hours:8,p_member_max_hours:24})}>Reset session policy</button></div>}</Card>{selected?.audit&&<Card title="Recent audit activity"><div className="member360"><pre>{JSON.stringify(selected.audit,null,2)}</pre></div></Card>}</>}
 </main></div>{menu&&<button className="scrim" onClick={()=>setMenu(false)} aria-label="Close menu"/>}{pinModal&&<div className="modalWrap"><div className="modal"><span className="eyebrow">CONFIRM TRANSACTION</span><h3>{pinModal.title}</h3><p>Enter your 4-digit transaction PIN to authorize this wallet debit.</p><input autoFocus className="pinInput" inputMode="numeric" maxLength={4} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,4))} placeholder="••••"/><div className="row"><button className="btn" onClick={()=>setPinModal(null)}>Cancel</button><button className="btn primary" disabled={pin.length!==4||busy} onClick={confirmDebit}>Confirm</button></div></div></div>}</div>
}
