import { notFound } from 'next/navigation';
import Link from 'next/link';
import { PublicShell } from '@/components/PublicShell';

type Page={title:string;eyebrow:string;intro:string;sections:{title:string;body:string}[]};
const pages:Record<string,Page>={
 'about':{title:'A cooperative built around steady progress.',eyebrow:'ABOUT US',intro:'Acres of Diamond Multipurpose Cooperative Society brings disciplined saving, member ownership and responsible access to credit into one transparent structure.',sections:[{title:'Member owned',body:'The cooperative exists to serve its members. Savings, shares, approvals and credit are tracked distinctly so obligations and benefits remain clear.'},{title:'Asset focused',body:'Our property thrift structure helps members deliberately accumulate toward property and other productive assets.'},{title:'Accountable operations',body:'Administrative actions are recorded, financial movements are ledger-backed and sensitive member actions use confirmation controls.'}]},
 'how-it-works':{title:'From account creation to active membership.',eyebrow:'HOW IT WORKS',intro:'Membership follows a clear sequence so every applicant knows what remains before activation.',sections:[{title:'1. Verify and identify',body:'Create an account, verify your email, submit your NIN and complete the membership registration form.'},{title:'2. Understand the rules',body:'Read the current bye-laws, accept them, pay the registration fee and meet the minimum share-capital requirement.'},{title:'3. Independent review',body:'A submitted application requires two distinct authorized reviewers before membership becomes active.'}]},
 'membership':{title:'Membership with a clear financial foundation.',eyebrow:'MEMBERSHIP',intro:'Start with the registration requirement and minimum share capital, then build your cooperative relationship through savings and participation.',sections:[{title:'Registration',body:'The current registration fee is ₦10,000, subject to cooperative policy.'},{title:'Share capital',body:'The current minimum share capital is ₦10,000. Shares represent member ownership and are tracked separately from savings.'},{title:'Digital onboarding',body:'Applicants can complete onboarding, track review status and see correction notes directly in the portal.'}]},
 'savings':{title:'Flexible savings plus purposeful property thrift.',eyebrow:'SAVINGS',intro:'Regular savings can adapt to the member while property thrift is a more disciplined path toward asset ownership.',sections:[{title:'Participative savings',body:'Save positive amounts based on the active savings scheme rules. Your contributions stay separate from wallet cash.'},{title:'Property thrift',body:'The current property thrift model is ₦10,000 weekly for 50 weeks, accumulating ₦500,000 when completed.'},{title:'Transaction controls',body:'A transaction PIN is requested only when a member confirms a wallet debit.'}]},
 'shares':{title:'Own a stake in the cooperative.',eyebrow:'SHARES',intro:'Share capital is not the same as a savings balance. It represents your ownership stake and supports the cooperative’s capital base.',sections:[{title:'Minimum capital',body:'The current minimum share capital for onboarding is ₦10,000.'},{title:'Separate accounting',body:'Share purchases are posted separately from wallet and savings balances.'}]},
 'loans':{title:'Credit designed around capacity and security.',eyebrow:'LOANS',intro:'Members can review eligibility, a reducing-balance quote and available savings/share security before submitting a loan application.',sections:[{title:'Reducing balance',body:'The active standard loan uses monthly reducing-balance interest under current policy.'},{title:'Member security',body:'Savings and share capital—not wallet cash—form the primary member security base.'},{title:'Guarantors',body:'Up to two active members may be used as guarantors when required, and their consent is recorded before review.'}]},
 'faqs':{title:'Common questions.',eyebrow:'FAQs',intro:'Answers to the questions members most often ask before joining.',sections:[{title:'Is the cooperative an investment scheme?',body:'No. It is a member-owned cooperative structure for saving, ownership, responsible credit and asset building.'},{title:'Can I join from outside Warri?',body:'Yes. The digital portal is designed so members can manage their cooperative relationship remotely.'},{title:'When is a transaction PIN required?',body:'It is requested at the final confirmation step for member-initiated wallet debits, not for ordinary navigation or wallet funding.'}]},
 'contact':{title:'Talk to the cooperative.',eyebrow:'CONTACT',intro:'Use the member portal for account-specific support or reach the cooperative office for general enquiries.',sections:[{title:'Office',body:'Jacknovo Plaza, 75 Warri–Sapele Road, beside the Water Board, Warri, Delta State.'},{title:'Member support',body:'Signed-in members can submit and track complaints directly from the Support section of the portal.'}]},
 'privacy':{title:'Privacy and member data.',eyebrow:'PRIVACY',intro:'The cooperative collects only the information needed to operate membership, compliance and financial services.',sections:[{title:'Identity data',body:'Identity and KYC information is restricted to authorized workflows and should not be disclosed publicly.'},{title:'Financial records',body:'Transactions, balances, approvals and audit records are retained to support accountability and reconciliation.'}]},
 'terms':{title:'Using the digital cooperative platform.',eyebrow:'TERMS',intro:'Members are responsible for keeping account credentials and transaction PINs confidential and for reviewing transaction details before confirmation.',sections:[{title:'Accurate information',body:'Membership and KYC information submitted through the platform must be accurate and current.'},{title:'Approvals',body:'Submission does not itself mean approval. Membership, loans, withdrawals and other controlled actions follow their applicable review workflow.'}]},
 'bye-laws':{title:'The cooperative bye-laws.',eyebrow:'BYE-LAWS',intro:'The currently published bye-laws govern membership and cooperative operations. Applicants must read and accept the current version during onboarding.',sections:[{title:'Current version',body:'The portal displays the currently published version and records the version accepted by each applicant.'},{title:'Acceptance',body:'A new published version may require renewed acceptance before certain onboarding or membership actions can proceed.'}]},
};
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const{slug}=await params;return pages[slug]?{title:pages[slug].title}:{};}
export default async function Info({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const p=pages[slug];if(!p)notFound();return <PublicShell><section className="infoHero"><div className="container infoHeroInner"><p className="eyebrow">{p.eyebrow}</p><h1 className="display smallDisplay">{p.title}</h1><p>{p.intro}</p></div></section><section className="container publicSection"><div className="infoGrid">{p.sections.map(s=><article className="publicCard" key={s.title}><h2>{s.title}</h2><p>{s.body}</p></article>)}</div><div className="infoAction"><Link className="btn primary" href="/register">Become a member</Link><Link className="btn" href="/login">Member login</Link></div></section></PublicShell>}
