'use client';
import Link from 'next/link';
import { FormEvent,useState } from 'react';
import { supabase } from '@/lib/supabase';
export default function Register(){
 const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMsg('');const emailRedirectTo=`${location.origin}/auth/callback?next=/portal`;const{error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo}});setBusy(false);setMsg(error?error.message:'Account created. Check your email and verify your account, then continue onboarding.');}
 async function google(){setBusy(true);setMsg('');const redirectTo=`${location.origin}/auth/callback?next=/portal`;const{error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo}});if(error){setBusy(false);setMsg(error.message)}}
 return <main id="main" className="authPage"><section className="authVisual"><Link href="/" className="logoBox" aria-label="Home">AD</Link><span className="eyebrow">JOIN THE COOPERATIVE</span><h1>Turn regular contributions into real progress.</h1><p>Create your account, complete identity and membership steps, then follow your application through independent review.</p><div className="authHighlights"><span>₦10,000 registration</span><span>₦10,000 minimum shares</span><span>Property thrift pathway</span></div></section><section className="authPanel"><form className="authCard" onSubmit={submit}><p className="eyebrow">START MEMBERSHIP</p><h2>Create account</h2><p className="muted">Use an email address you can access. You will verify it before final submission.</p><button type="button" className="btn google" onClick={google} disabled={busy}>Continue with Google</button><div className="divider"><span>or use email</span></div><label>Email address<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/><small>Use at least 8 characters.</small></label>{msg&&<div className={`alert ${msg.startsWith('Account created')?'':'error'}`}>{msg}</div>}<button className="btn primary wide" disabled={busy}>{busy?'Creating…':'Create account'}</button><p className="small muted center">Already registered? <Link href="/login">Sign in</Link></p></form></section></main>}
