'use client';
import Link from 'next/link';
import {FormEvent,useState} from 'react';
import {useRouter} from 'next/navigation';
import {friendlyError,supabase} from '../../lib/supabase';

export default function Register(){
 const router=useRouter();const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg('');const fd=new FormData(e.currentTarget);const email=String(fd.get('email'));const password=String(fd.get('password'));const metadata={first_name:String(fd.get('firstName')),middle_name:String(fd.get('middleName')||''),surname:String(fd.get('surname')),phone:String(fd.get('phone'))};const {data,error}=await supabase.auth.signUp({email,password,options:{data:metadata,emailRedirectTo:`${location.origin}/auth/callback`}});setBusy(false);if(error)return setMsg(friendlyError(error.message));if(data.session)router.replace('/onboarding');else setMsg('Account created. Check your email to verify your address, then continue your membership application.');}
 async function google(){setBusy(true);setMsg('');const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${location.origin}/auth/callback`,queryParams:{access_type:'offline',prompt:'consent'}}});if(error){setBusy(false);setMsg(friendlyError(error.message));}}
 return <main className="authPage"><section className="authVisual"><Link href="/" className="brand"><span className="brandMark">AD</span><span>Acres of Diamond<small style={{color:'#bdd6ca'}}>Multipurpose Cooperative Society</small></span></Link><p className="eyebrow" style={{color:'#a5dfbf',marginTop:45}}>Membership begins here</p><h1>Start building with the cooperative.</h1><p>Create an applicant account first. You become an active member after onboarding, KYC, bye-law acceptance, the registration/share payment and two independent approvals.</p></section><section className="authPanel"><form className="card authCard" onSubmit={submit}><Link href="/" className="brand"><span className="brandMark">AD</span><span>Acres of Diamond<small>Multipurpose Cooperative Society</small></span></Link><h1>Create account</h1><p className="muted">Registration fee: ₦10,000 · Minimum share capital: ₦10,000.</p>{msg&&<div className={msg.startsWith('Account created')?'alert success':'alert error'}>{msg}</div>}<div className="formGrid"><button type="button" className="btn" onClick={google} disabled={busy}>Continue with Google</button><div className="divider">or register with email</div><div className="two"><label className="label">First name<input className="field" required minLength={2} name="firstName" autoComplete="given-name"/></label><label className="label">Middle name<input className="field" name="middleName" autoComplete="additional-name"/></label></div><label className="label">Surname<input className="field" required minLength={2} name="surname" autoComplete="family-name"/></label><label className="label">Phone number<input className="field" required name="phone" type="tel" placeholder="+2348012345678" autoComplete="tel"/></label><label className="label">Email<input className="field" required name="email" type="email" autoComplete="email"/></label><label className="label">Password<input className="field" required name="password" type="password" minLength={10} autoComplete="new-password"/><small className="muted">Use at least 10 characters. Your transaction PIN will be separate.</small></label><button className="btn primary" disabled={busy}>{busy?'Creating account…':'Create applicant account'}</button></div><p className="muted" style={{fontSize:12}}>By creating an account, you agree to complete truthful KYC information and to review the current cooperative bye-laws before final submission.</p><p className="muted" style={{textAlign:'center',fontSize:13}}>Already registered? <Link href="/login" style={{color:'var(--green)',fontWeight:850}}>Log in</Link></p></form></section></main>
}
