'use client';
import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { supabase } from '@/lib/supabase';

export default function LoginPage(){
 const router=useRouter();const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMsg('');const{error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error)return setMsg(error.message);router.replace('/portal');router.refresh()}
 async function google(){setBusy(true);setMsg('');const redirectTo=`${location.origin}/auth/callback?next=/portal`;const{error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo}});if(error){setBusy(false);setMsg(error.message)}}
 return <main id="main" className="authPage"><section className="authVisual"><Link href="/" className="logoBox" aria-label="Home">AD</Link><span className="eyebrow">SECURE MEMBER ACCESS</span><h1>Build assets. Grow together.</h1><p>One place for membership, savings, shares, loans and cooperative administration.</p><div className="authHighlights"><span>Ledger-backed money flows</span><span>Transparent approvals</span><span>Mobile-ready access</span></div></section><section className="authPanel"><form className="authCard" onSubmit={submit}><Link className="mobileBrand" href="/"><span className="logoBox">AD</span><b>Acres of Diamond</b></Link><p className="eyebrow">WELCOME BACK</p><h2>Sign in securely</h2><p className="muted">Continue your application or access your cooperative account.</p><button type="button" className="btn google" onClick={google} disabled={busy}>Continue with Google</button><div className="divider"><span>or use email</span></div><label>Email address<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="you@example.com"/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={8} placeholder="Enter your password"/></label>{msg&&<div className="alert error" role="alert">{msg}</div>}<button className="btn primary wide" disabled={busy}>{busy?'Signing in…':'Sign in'}</button><div className="authLinks"><Link href="/forgot-password">Forgot password?</Link><span>New member? <Link href="/register">Create account</Link></span></div></form></section></main>
}
